### ISSUE TITLE
Any instructions for applying to custom datasets?

### ISSUE THREAD

**Issue by sgbaird** [lrcfmd/PhaseSelect#1]
Nice work btw, looking forward to digging through the paper a bit more.

**Comment by DrewNow** [comment]
Thanks for this, Sterling.

Please take a look at the updated README.md and template_generic*py files.

Sorry for taking long to close the issue - I am not the owner of this group's GitHub page, and don't get notifications when issues are raised. Feel free to drop a line to andrij@liverpool.ac.uk if you have any queries in the future.

Best
Andrij
